### ISSUE TITLE
replace go-version

### ISSUE THREAD

**Issue by fromanirh** [k8stopologyawareschedwg/resource-topology-exporter#83]
In the e2e tests we use https://github.com/hashicorp/go-version which is a fine package but whose license is not auto-allowed by CNCF (see: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md)
In order to be as much friendly as possible with CNCF, we should replace this dependency with something with a auto-allowed license, like https://github.com/aquasecurity/go-version

Finally, it may be needed to revisit how we auto-create the version (nowadays just using `git describe --tags`), which I'm not sure it's a well formed SEMVER anyway.

**Comment by jlojosnegros** [comment]
# Regarding how we auto-create versions.
## Context
### Semver format
Semver versions use the format
```
MAJOR.MINOR.PATCH-pre_release+metadata
```
Here we are concern about `pre_release` and `metadata` fields mainly.

#### [pre-release](https://semver.org/#spec-item-9)
Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]

#### [metadata](https://semver.org/#spec-item-10)
Build metadata MUST be ignored when determining version precedence

### `git describe`
From [documentation](https://git-scm.com/docs/git-describe) `git describe --tags` command returns the closest reachable tag from a given commit and, if the tag does **not** point to the commit itself, it add some suffixes.
Ej: For a commit without a tag:
```bash
$> git describe --tags
v0.2.5-68-g91f2c330
```
Being:
- `v0.2.5`: Closest tag found
- `68`: Number of commits on top of the tag
- `g91f2c330`: hash of the last commit

## Problems

### Current tag format is not a valid semver
As we can see in [semver homepage](https://semver.org/#is-v123-a-semantic-version), using 'v' as prefix is not valid.
This seems a minor problem.

### Semver [precedence rules.](https://semver.org/#spec-item-11)
Here is the main problem.
With `git describe` command we build new versions adding a suffix to the tag, that is adding a `pre_release` field using semver terminology, so a version with a suffix is "greater" (newest) than the one without it.
```
v0.2.5 < v0.2.5-68-g91f2c330
```

However, as we can see in the semver precedence rules, any version with a `pre_release` field is considered "less" than (oldest) the one without it, because pre-released versions seems to be the working versions leading to the release of the version mentioned.

```
v0.2.5-68-g91f2c330 < v0.2.5 
```

## Possible solutions.
The main problems seems to be that pre-released are meant to be used when you already know your next release version number which makes it difficult to handle nightly or development versions properly. 
Some [discussions have been held](https://github.com/semver/semver/issues/200) regarding this issue, but it does not seems probably to see a change in semver for this.

At this point I can only figure two possible solutions:
- To use `metadata` field to handle develop versions.
  - The problem is that semver encourage to ignore `metadata` field when calculating precedence 
- To "foresee" the next version ( maybe incrementing patch) and keep using `pre-release` field 
  - The problem is that the next version could end not being the one we foresee.

### Way forward
This is a common problem so there are some tools trying to help on solving it. Currently I am investigating these:
- https://github.com/meinto/git-semver
- https://github.com/markchalloner/git-semver
- https://github.com/mdomke/git-semver

**Comment by fromanirh** [comment]
solved using https://github.com/k8stopologyawareschedwg/resource-topology-exporter/pull/88
